CREATE EXTERNAL TABLE `r_seoul_rescue`(
  `msfrtn_resc_reprt_no` string, 
  `acdnt_cause` string, 
  `prcs_result_se_nm` string, 
  `dclr_ymd` bigint, 
  `dclr_tm` bigint, 
  `dclr_yr` bigint, 
  `season_se_nm` string, 
  `qtr_se` bigint, 
  `dclr_mnth` bigint, 
  `dclr_day` bigint, 
  `dclr_hour` bigint, 
  `dclr_min` bigint, 
  `daywk` string, 
  `dsp_ymd` double, 
  `dsp_tm` double, 
  `dsp_yr` double, 
  `dsp_mnth` double, 
  `dsp_day` double, 
  `dsp_hour` double, 
  `dsp_min` double, 
  `spt_arvl_ymd` double, 
  `spt_arvl_tm` double, 
  `spt_arvl_yr` double, 
  `spt_arvl_mnth` double, 
  `spt_arvl_day` double, 
  `spt_arvl_hour` double, 
  `spt_arvl_min` double, 
  `resc_cmptn_ymd` double, 
  `resc_cmptn_tm` double, 
  `resc_cmptn_yr` double, 
  `resc_cmptn_mnth` double, 
  `resc_cmptn_day` double, 
  `resc_cmptn_hour` double, 
  `resc_cmptn_min` double, 
  `hmg_ymd` double, 
  `hmg_tm` double, 
  `hmg_yr` double, 
  `hmg_mnth` double, 
  `hmg_day` double, 
  `hmg_hour` double, 
  `hmg_min` double, 
  `sido_nm` string, 
  `sigungu_nm` string, 
  `emd_nm` string, 
  `cty_frmvl_se_nm` string, 
  `emd_se_nm` string, 
  `gis_x_axis` double, 
  `gis_y_axis` double, 
  `spt_frstt_dist` string, 
  `acdnt_place_nm` string, 
  `acdnt_place_detail_nm` string, 
  `acdnt_cause_asort_nm` string, 
  `frstt_nm` string, 
  `ward_nm` string, 
  `lfdau_nm` string, 
  `time_unit_tmprt` double, 
  `time_unit_rainqty` double, 
  `time_unit_ws` double, 
  `time_unit_wd` double, 
  `time_unit_humidity` double, 
  `time_unit_msnf` string, 
  `time_unit` double)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ',' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://cloud9-project-batch/seoul_rescue'
TBLPROPERTIES (
  'CrawlerSchemaDeserializerVersion'='1.0', 
  'CrawlerSchemaSerializerVersion'='1.0', 
  'UPDATED_BY_CRAWLER'='crw_seoul_rescue_raw', 
  'areColumnsQuoted'='false', 
  'averageRecordSize'='455', 
  'classification'='csv', 
  'columnsOrdered'='true', 
  'compressionType'='none', 
  'delimiter'=',', 
  'objectCount'='1', 
  'recordCount'='958153', 
  'sizeKey'='435959694', 
  'skip.header.line.count'='1', 
  'transient_lastDdlTime'='1735893921', 
  'typeOfData'='file')