CREATE EXTERNAL TABLE `rw_seoul_rescue`(
  `msfrtn_resc_reprt_no` string, 
  `acdnt_cause` string, 
  `prcs_result_se_nm` string, 
  `dclr_ymd` string, 
  `dclr_tm` string, 
  `season_se_nm` string, 
  `qtr_se` string, 
  `dclr_hour` string, 
  `dclr_min` string, 
  `daywk` string, 
  `dsp_ymd` string, 
  `dsp_tm` string, 
  `dsp_yr` string, 
  `dsp_mnth` string, 
  `dsp_day` string, 
  `dsp_hour` string, 
  `dsp_min` string, 
  `spt_arvl_ymd` string, 
  `spt_arvl_tm` string, 
  `spt_arvl_yr` string, 
  `spt_arvl_mnth` string, 
  `spt_arvl_day` string, 
  `spt_arvl_hour` string, 
  `spt_arvl_min` string, 
  `resc_cmptn_ymd` string, 
  `resc_cmptn_tm` string, 
  `resc_cmptn_yr` string, 
  `resc_cmptn_mnth` string, 
  `resc_cmptn_day` string, 
  `resc_cmptn_hour` string, 
  `resc_cmptn_min` string, 
  `hmg_ymd` string, 
  `hmg_tm` string, 
  `hmg_yr` string, 
  `hmg_mnth` string, 
  `hmg_day` string, 
  `hmg_hour` string, 
  `hmg_min` string, 
  `sido_nm` string, 
  `sigungu_nm` string, 
  `emd_nm` string, 
  `cty_frmvl_se_nm` string, 
  `emd_se_nm` string, 
  `gis_x_axis` double, 
  `gis_y_axis` double, 
  `spt_frstt_dist` double, 
  `acdnt_place_nm` string, 
  `acdnt_place_detail_nm` string, 
  `acdnt_cause_asort_nm` string, 
  `frstt_nm` string, 
  `ward_nm` string, 
  `lfdau_nm` string, 
  `time_unit_tmprt` string, 
  `time_unit_rainqty` string, 
  `time_unit_ws` string, 
  `time_unit_wd` string, 
  `time_unit_humidity` string, 
  `time_unit_msnf` string, 
  `time_unit` string)
PARTITIONED BY ( 
  `dclr_yr` string, 
  `dclr_mnth` string, 
  `dclr_day` string)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ',' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://cloud9-batch-raw/seoul_rescue_raw_partitioned'
TBLPROPERTIES (
  'classification'='csv', 
  'isRegisteredWithLakeFormation'='false', 
  'spark.sql.create.version'='3.5.2-amzn-1', 
  'spark.sql.partitionProvider'='catalog', 
  'spark.sql.sources.schema.numPartCols'='3', 
  'spark.sql.sources.schema.numParts'='2', 
  'spark.sql.sources.schema.part.0'='{\"type\":\"struct\",\"fields\":[{\"name\":\"msfrtn_resc_reprt_no\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"acdnt_cause\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"prcs_result_se_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dclr_ymd\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dclr_tm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"season_se_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"qtr_se\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dclr_hour\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dclr_min\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"daywk\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dsp_ymd\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dsp_tm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dsp_yr\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dsp_mnth\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dsp_day\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dsp_hour\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dsp_min\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_arvl_ymd\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_arvl_tm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_arvl_yr\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_arvl_mnth\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_arvl_day\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_arvl_hour\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_arvl_min\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"resc_cmptn_ymd\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"resc_cmptn_tm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"resc_cmptn_yr\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"resc_cmptn_mnth\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"resc_cmptn_day\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"resc_cmptn_hour\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"resc_cmptn_min\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hmg_ymd\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hmg_tm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hmg_yr\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hmg_mnth\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hmg_day\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hmg_hour\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hmg_min\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"sido_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"sigungu_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"emd_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"cty_frmvl_se_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"emd_se_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"gis_x_axis\",\"type\":\"double\",\"nullable\":true,\"metadata\":{}},{\"name\":\"gis_y_axis\",\"type\":\"double\",\"nullable\":true,\"metadata\":{}},{\"name\":\"spt_frstt_dist\",\"type\":\"double\",\"nullable\":true,\"metadata\":{}},{\"name\":\"acdnt_place_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"acdnt_place_detail_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"acdnt_cause_asort_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"frstt_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"ward_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"lfdau_nm\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"time_unit_tmprt\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"time_unit_rainqty\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"time_unit_ws\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"time_unit_wd\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"time_unit_humidity\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"time_unit_msnf\",\"type\":\"string\",\"nullable\"', 
  'spark.sql.sources.schema.part.1'=':true,\"metadata\":{}},{\"name\":\"time_unit\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dclr_yr\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dclr_mnth\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"dclr_day\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}]}', 
  'spark.sql.sources.schema.partCol.0'='dclr_yr', 
  'spark.sql.sources.schema.partCol.1'='dclr_mnth', 
  'spark.sql.sources.schema.partCol.2'='dclr_day')